name: TPP-MLIR Benchmarks

on:
  workflow_dispatch:
    inputs:
      RUN_EMR_BENCH:
        description: "Run on Emerald Rapids"
        type: boolean
        default: true
      RUN_ZEN_BENCH:
        description: "Run on Zen5"
        type: boolean
        default: true
      RUN_ARL_BENCH:
        description: "Run on ARL"
        type: boolean
        default: true
  push:
    branches:
      - 'main'
  pull_request:

env:
  NPROCS_LIMIT_LINK: 8
  SRUN: ${HOME}/srun.sh
  NUM_ITER: 100

jobs:
  Check_LLVM:
    if: |
      (github.event_name == 'push') || (github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'benchmark')) ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'benchmark-full'))
    uses: ./.github/workflows/tpp-llvm.yml
    secrets: inherit

  TPP-MLIR-EMR-BASE:
    runs-on: pcl-tiergarten
    if: |
      (github.event_name == 'push') || 
      (github.event_name == 'workflow_dispatch' && inputs.RUN_EMR_BENCH) ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'benchmark')) ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'benchmark-full'))
    needs: Check_LLVM
    steps:
      - uses: actions/checkout@v4
      - name: Emerald Rapids Base
        run: |-
          CMD="KIND=Release COMPILER=clang LINKER=lld BENCHMARK_NUM_ITER=${{ env.NUM_ITER }} \
               ${{ github.workspace }}/scripts/github/benchmark.sh -b -p"
          ${{ env.SRUN }} --partition=emr --time=0:30:00 --constraint=\"notrb\" -- $CMD

  TPP-MLIR-EMR-OMP:
    runs-on: pcl-tiergarten
    if: |
      (github.event_name == 'push') || 
      (github.event_name == 'workflow_dispatch' && inputs.RUN_EMR_BENCH) ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'benchmark')) ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'benchmark-full'))
    needs: Check_LLVM
    steps:
      - uses: actions/checkout@v4
      - name: Emerald Rapids OpenMP
        run: |-
          CMD="KIND=Release COMPILER=clang LINKER=lld BENCHMARK_NUM_ITER=${{ env.NUM_ITER }} \
               ${{ github.workspace }}/scripts/github/benchmark.sh -o"
          ${{ env.SRUN }} --partition=emr --time=0:30:00 --constraint=\"notrb\" -- $CMD

  TPP-MLIR-ZEN-BASE:
    runs-on: pcl-tiergarten
    if: |
      (github.event_name == 'push') || 
      (github.event_name == 'workflow_dispatch' && inputs.RUN_ZEN_BENCH) ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'benchmark-full'))
    needs: Check_LLVM
    steps:
      - uses: actions/checkout@v4
      - name: Zen5 Base
        run: |-
          CMD="KIND=Release COMPILER=clang LINKER=lld CHECK=1 BENCHMARK_NUM_ITER=${{ env.NUM_ITER }} \
               ${{ github.workspace }}/scripts/github/benchmark.sh -b -p"
          ${{ env.SRUN }} --partition=zen5 --time=0:30:00 -- $CMD

  TPP-MLIR-ZEN-OMP:
    runs-on: pcl-tiergarten
    if: |
      (github.event_name == 'push') || 
      (github.event_name == 'workflow_dispatch' && inputs.RUN_ZEN_BENCH) ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'benchmark-full'))
    needs: Check_LLVM
    steps:
      - uses: actions/checkout@v4
      - name: Zen5 OpenMP
        run: |-
          CMD="KIND=Release COMPILER=clang LINKER=lld BENCHMARK_NUM_ITER=${{ env.NUM_ITER }} \
               ${{ github.workspace }}/scripts/github/benchmark.sh -o"
          ${{ env.SRUN }} --partition=zen5 --time=0:30:00 -- $CMD

  TPP-MLIR-ARL-BASE:
    runs-on: pcl-tiergarten
    if: |
      (github.event_name == 'push') ||
      (github.event_name == 'workflow_dispatch' && inputs.RUN_ARL_BENCH) ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'benchmark-full'))
    needs: Check_LLVM
    steps:
      - uses: actions/checkout@v4
      - name: ARL Base
        run: |-
          CMD="KIND=Release COMPILER=clang LINKER=lld CHECK=1 BENCHMARK_NUM_ITER=${{ env.NUM_ITER }} \
                ${{ github.workspace }}/scripts/github/benchmark.sh -b -p"
          ${{ env.SRUN }} --partition=arl --time=0:30:00 -- $CMD

  TPP-MLIR-ARL-OMP:
    runs-on: pcl-tiergarten
    if: |
      (github.event_name == 'push') ||
      (github.event_name == 'workflow_dispatch' && inputs.RUN_ARL_BENCH) ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'benchmark-full'))
    needs: Check_LLVM
    steps:
      - uses: actions/checkout@v4
      - name: ARL OpenMP
        run: |-
          CMD="KIND=Release COMPILER=clang LINKER=lld BENCHMARK_NUM_ITER=${{ env.NUM_ITER }} \
                ${{ github.workspace }}/scripts/github/benchmark.sh -o"
          ${{ env.SRUN }} --partition=arl --time=0:30:00 -- $CMD
